name: "Fortran Lint"
description: "Simple Fortran Lint, currently checks for trailing whitespace and Tab characters"
inputs:
   failure:
      description: "Cause action to fail if lint errors found"
      required: false
      default: true
outputs:
   lintSuccess:
      description: "indicates if the the lint processes passed (true) or failed (false)"
runs:
   using: "docker"
   image: "Dockerfile"
   args: ["${{ inputs.failure }}"]
branding:
   icon: "shield"
   color: "blue"



# find . -type f -exec file {} \; | grep '\(Bourne-Again\|POSIX\|Korn\) shell' | awk -F : '{print $1}'
